Ii = int(input("Investment Price at Purchase: "))
Is = int(input("Investment Price at Selling: "))
Tr = int(input("Tax Rate When Sold: "))
CPIi = int(input("CPI at purchase: "))
CPIs = int(input("CPI at sale: "))
CPIdif = int(CPIs-CPIi)
print(CPIdif)
CPIdifper = int(CPIdif/CPIi)
print(CPIdifper)
Ddifper = CPIi/CPIs
print(Ddifper)
ValueRelative = int(Ddifper/Is)
print(ValueRelative)
Gain = int(Is-Ii)
print(Gain)
T = int(Tr*Gain)
print(T)
PostT = int(Is-T)
print(PostT)
PostTinit = int(PostT/Ddifper)
print(PostTinit)
Truth = int(PostTinit-Ii)
print("True Value is... " + str(Truth))
